### ISSUE TITLE
Nested \( \) Highlight

### ISSUE THREAD

**Issue by sleepymalc** [jlelong/vscode-latex-basics#67]
- The syntax highlight of `\( \)` behaves weird in, e.g., `\hyperref[]{}`
<img width="180" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/60427058/6b221286-306a-427a-b032-93fe8577714f">

- The previous version (e.g., version 9.7.0) is the expected highlight behavior
<img width="174" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/60427058/cd9a357b-21cd-48db-8b82-3e5a370762a0">

A minimal example to reproduce the issue

`\hyperref[\(\)]{\(\)}`

- VS Code Version: 1.82.2
- OS Version: macOS 13.5.2 (22G91)
- LaTeX-Workshop version if you use it: 9.13.4

**Comment by jlelong** [comment]
Actually, I do not think the new rendering of `hyperref` is a bug. Let's have a closer look.

First, disabling `editor.bracketPairColorization.enabled` removes what you call the weird colouring 

<img width="216" alt="Capture d’écran 2023-09-17 à 17 31 11" src="https://github.com/jlelong/vscode-latex-basics/assets/2910140/e962096a-9a94-452a-b857-7f8b161abfa1">

Second, why did not we have this weird colouring before version `1.5.3` of the LaTeX grammar? This is because `\(...\)` inside the first bracket pair was considered as delimiters of a math block before #59. This was actually wrong. It seems to me that the new grammar is better and uses more relevant scopes.

Btw, `\hyperref` expects a label as its optional argument. Isn't it a bit weird to find `\(` inside a label? I would even have thought this these are not accepted as part of a label.

**Comment by sleepymalc** [comment]
I understand the expected behavior for the first optional argument, i.e., `\hyperlink[\(\)]{some text...}`, is probably not correct and should not be used in the first place. 
However, a more concerning problem is for the second argument, i.e., `\hyperlink[some label]{\(\)}`: this is what I use on a daily basis. However, now it's not rendered in the usual way. I think a potential reason is the following:
<img width="506" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/60427058/a53c069d-2de4-4886-aa54-7d6b7da7b1d3">
As you can see, the scope inside `\(\)` is not even math.
> This causes me other problems when using other extensions (which is irrelevant to this one, though). 

I'm not sure whether this is a VSCode bug or something else.

**Comment by jlelong** [comment]
You are right the second argument in `\hyperlink[some label]{some text}` is not matched against the LaTeX syntax, hence math is not highlighted. I will investigate if it can be fixed.
