### ISSUE TITLE
Variables in the cctab module are not highlighted

### ISSUE THREAD

**Issue by SwitWu** [jlelong/vscode-latex-basics#92]
Variables in the cctab module are not highlighted.

A minimal example to reproduce the issue

```tex
\c_@@_package_cctab
```

- VS Code Version: 1.88.1 (Universal)
- OS Version: macOS Sonoma
- LaTeX-Workshop version if you use it: v9.20.1

**Comment by SwitWu** [comment]
The same for variables in the skip module such as `\c_module_description_skip`

**Comment by zepinglee** [comment]
https://github.com/jlelong/vscode-latex-basics/blob/5d7c2a4e451a932b776f6d9342087be6a1e8c0a1/src/LaTeX.tmLanguage.base.yaml#L795-L799

Perhaps we can extend the `(?:bitset|clist|dim|fp|int|muskip|str|tl|bool|box|coffin|flag|fparray|intarray|ior|iow|prop|regex|seq)` pattern to `[a-z]+` so that we don't need to modify this with additional variable types?

**Comment by jlelong** [comment]
I have just given it a try. Let's wait and see
